<?php
/*
 * Author:      Roland Galibert
 * Date:        March 31, 2016
 * For:         CSCI E-15 Dynamic Web Applications, Spring 2016 - Project 3
 * Purpose:     Controller for random user generator tool
 */

namespace App\Http\Controllers\rug;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Controllers\rug\RUG;

class RUGController extends Controller {

        /*
         * Validation rules
         */
        private static $rules = [
                        'rug_selected_fields' => 'required',
                        'rug_num_records' => 'required|integer|min:1|max:100',
                ];
        
        /*
         * Validation error messages
         */
        private static $messages = [
                        'rug_selected_fields.required' => 'Please select at least one data field.',
                        'rug_num_records.required' => 'Please enter the number of records you want.',
                        'rug_num_records.integer' => 'Number of records must be an integer between 1 and 100',
                        'rug_num_records.min' => 'Number of records must be an integer between 1 and 100',
                        'rug_num_records.max' => 'Number of records must be an integer between 1 and 100',
                ];

        /*
         * Get method for random user generation application
         */
        public function getIndex() {
                $output = "";
                
                /*
                 * HTML for $available_fields, $selected_fields HTML generated by
                 * RUG class.
                 */
                $available_fields = RUG::availableFieldsHTML();
                $selected_fields = RUG::selectedFieldsHTML();
                return view('rug.index', [
                                'output' => $output,
                                'available_fields' => $available_fields,
                                'selected_fields' => $selected_fields
                        ]);
        }
        
        /*
         * Post method for random user generation application
         */
        public function postIndex(Request $request) {
                
                /*
                 * Available, selected field options saved to RUG class static
                 * variables.
                 */
                RUG::$available_fields = $request->input('rug_available_fields');
                RUG::$selected_fields = $request->input('rug_selected_fields');
                
                /*
                 * HTML for $available_fields, $selected_fields HTML generated by
                 * RUG class.
                 */
                $available_fields = RUG::availableFieldsHTML();
                $selected_fields = RUG::selectedFieldsHTML();
                
                $this->validate($request, self::$rules, self::$messages);
                
                /*
                 * Call RUG class method to generate data creation script.
                 */
                $output = RUG::generateDataScript($request->input('rug_selected_fields'),
                        intval($request->input('rug_num_records')),
                        intval($request->input('rug_output')));
                return view('rug.index', [
                                'output' => $output,
                                'available_fields' => $available_fields,
                                'selected_fields' => $selected_fields
                        ]);
        }

}